<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mikepad</AssemblyName>
    <RootNamespace>Mikepad</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\Mikepad.ico</ApplicationIcon>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
</Project>
